=== eux90/DP2/Assignment1b/temp528458271/xsd/nffgInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://NFFG.dp2.polito.it"
	targetNamespace="http://NFFG.dp2.polito.it">

	<!-- some constraints, others below -->
	<element name="nffgInfo" type="tns:nffgInfoType">
		<!-- each NFFG has a unique name in the NFFG Set -->
		<key name="nffgKey">
			<selector xpath="nffgSet/nffg" />
			<field xpath="@name" />
		</key>
		<!-- each Policy has a unique name in the Policy Set -->
		<key name="trvPolicyKey">
			<selector xpath="policySet/*/*" />
			<field xpath="@name" />
		</key>
		<!-- each Policy refer to an existing NFFG -->
		<keyref name="nffgRef" refer="tns:nffgKey">
			<selector xpath="policySet/*/*" />
			<field xpath="@nffg" />
		</keyref>
	</element>

	<!-- the root element contains NFFGs and Policies -->
	<complexType name="nffgInfoType">
		<sequence>
			<element name="nffgSet" type="tns:nffgSetType" />
			<element name="policySet" type="tns:policySetType" />
		</sequence>
	</complexType>

	<!-- general container for NFFGs -->
	<complexType name="nffgSetType">
		<sequence>
			<element name="nffg" type="tns:nffgType" minOccurs="0"
				maxOccurs="unbounded">

				<!-- each srcNode or dstNode in the linkSet should refer to a node in 
					the nodeSet -->
				<keyref name="nodeRef1" refer="tns:nodeKey">
					<selector xpath="linkSet/link/*" />
					<field xpath="." />
				</keyref>
			</element>
		</sequence>
	</complexType>

	<!-- definition of a NFFG -->
	<complexType name="nffgType">
		<sequence>
			<element name="nodeSet" type="tns:nodeSetType">
			
				<!-- each nodeName is unique inside a nodeSet -->
				<key name="nodeKey">
					<selector xpath="node" />
					<field xpath="@name" />
				</key>
			</element>
			<element name="linkSet" type="tns:linkSetType">
			
				<!-- each linkName is unique inside a linkSet -->
				<key name="linkKey">
					<selector xpath="link" />
					<field xpath="@name" />
				</key>
			</element>
		</sequence>
		<attribute name="name" type="tns:IDType" use="required"/>
		<attribute name="date" type="dateTime" use="required" />
	</complexType>
	
	<!-- general container for Nodes -->
	<complexType name="nodeSetType">
		<sequence>
			<element name="node" type="tns:nodeType" minOccurs="0"
				maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<!-- general container for Links -->
	<complexType name="linkSetType">
		<sequence>
			<element name="link" type="tns:linkType" minOccurs="0"
				maxOccurs="unbounded">
				
				<!-- source and destination node should be different in a link-->
				<unique name="sourceAndDestinationDifferent">
					<selector xpath="srcNode | dstNode" />
					<field xpath="." />
				</unique>
			</element>
		</sequence>
	</complexType>

	<!-- definition of a Node -->
	<complexType name="nodeType">
		<attribute name="name" type="tns:IDType" use="required"/>
		<attribute name="type" type="tns:funcType" use="required"/>
	</complexType>

	<!-- definition of a Link -->
	<complexType name="linkType">
		<group ref="tns:srcAndDstNodeGroup" />
		<attribute name="name" type="tns:IDType" use="required"/>
	</complexType>

	<!-- definition of a pair of Source and Destination Nodes -->
	<group name="srcAndDstNodeGroup">
		<sequence>
			<element name="srcNode" type="tns:IDType" />
			<element name="dstNode" type="tns:IDType" />
		</sequence>
	</group>

	<!-- definition of a unique identifier -->
	<simpleType name="IDType">
		<restriction base="string">
			<pattern value="[a-zA-Z]+[a-zA-Z0-9]*" />
		</restriction>
	</simpleType>

	<!-- definition of FunctionalTypes -->
	<simpleType name="funcType">
		<restriction base="string">
			<enumeration value="CACHE" />
			<enumeration value="DPI" />
			<enumeration value="FW" />
			<enumeration value="MAIL_CLIENT" />
			<enumeration value="MAIL_SERVER" />
			<enumeration value="NAT" />
			<enumeration value="SPAM" />
			<enumeration value="VPN" />
			<enumeration value="WEB_CLIENT" />
			<enumeration value="WEB_SERVER" />
		</restriction>
	</simpleType>

	<!-- general container for Policies -->
	<complexType name="policySetType">
		<sequence>
			<element name="rchPolicySet" type="tns:rchPolicySetType" />
			<element name="trvPolicySet" type="tns:trvPolicySetType" />
		</sequence>
	</complexType>
	
	<!-- container for ReachabilityPolicies -->
	<complexType name="rchPolicySetType">
		<sequence>
			<element name="rchPolicy" type="tns:rchPolicyType" minOccurs="0"
				maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>
	
	<!-- container for TraversalPolicies -->
	<complexType name="trvPolicySetType">
		<sequence>
			<element name="trvPolicy" type="tns:trvPolicyType" minOccurs="0"
				maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<!-- definition of a GeneralPolicy -->
	<complexType name="generalPolicyType">
		<sequence>
			<element name="verification" type="tns:verificationType" minOccurs="0" maxOccurs="1"/>
			<element name="isPositive" type="boolean" />
		</sequence>
		<attribute name="name" type="tns:IDType" use="required"/>
		<attribute name="nffg" type="tns:IDType" use="required"/>
	</complexType>

	<!-- if a policy is verified should have those elements -->
	<complexType name="verificationType">
		<sequence>
			<element name="result" type="boolean" />
			<element name="message" type="string" />
			<element name="date" type="dateTime" />
		</sequence>
	</complexType>

	<!-- definition of a ReachabilityPolicy -->
	<complexType name="rchPolicyType">
		<complexContent>
			<extension base="tns:generalPolicyType">
				<group ref="tns:srcAndDstNodeGroup" />
			</extension>
		</complexContent>
	</complexType>

	<!-- definition of a TraversalPolicy -->
	<complexType name="trvPolicyType">
		<complexContent>
			<extension base="tns:rchPolicyType">
				<sequence>
					<element name="functionList" type="tns:functionListType" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<!-- definition of the FunctionList of a TraversalPolicy -->
	<simpleType name="functionListType">
		<list itemType="tns:funcType"/>
	</simpleType>
</schema>

=== eux90/DP2/Assignment1b/xsd/nffgInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<mns:nffgInfo xmlns:mns="http://NFFG.dp2.polito.it"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://NFFG.dp2.polito.it nffgInfo.xsd">
	<nffgSet>
		<nffg name="N1" date="2016-03-20T20:32:50">
			<nodeSet>
				<node name="A1" type="NAT" />
				<node name="A2" type="FW" />
				<node name="A3" type="DPI" />
				<node name="A4" type="CACHE" />
			</nodeSet>
			<linkSet>
				<link name="B1">
					<srcNode>A1</srcNode>
					<dstNode>A3</dstNode>
				</link>
				<link name="B2">
					<srcNode>A3</srcNode>
					<dstNode>A4</dstNode>
				</link>
			</linkSet>
		</nffg>
		<nffg name="N2" date="2016-04-22T20:32:50">
			<nodeSet>
				<node name="A1" type="NAT" />
				<node name="A2" type="FW" />
				<node name="A5" type="DPI" />
				<node name="A6" type="CACHE" />
			</nodeSet>
			<linkSet>
				<link name="B1">
					<srcNode>A1</srcNode>
					<dstNode>A2</dstNode>
				</link>
				<link name="B2">
					<srcNode>A5</srcNode>
					<dstNode>A6</dstNode>
				</link>
			</linkSet>
		</nffg>
		</nffgSet>
	<policySet>
		<rchPolicySet>
			<rchPolicy name="P1" nffg="N2">
				<isPositive>1</isPositive>
				<srcNode>A1</srcNode>
				<dstNode>A2</dstNode>
			</rchPolicy>
			<rchPolicy name="P2" nffg="N1">
				<verification>
					<result>0</result>
					<message>Hello</message>
					<date>2016-04-22T20:32:50</date>
				</verification>
				<isPositive>1</isPositive>
				<srcNode>A1</srcNode>
				<dstNode>A2</dstNode>
			</rchPolicy>
		</rchPolicySet>
		<trvPolicySet>
			<trvPolicy name="P3" nffg="N1">
				<isPositive>1</isPositive>
				<srcNode>A1</srcNode>
				<dstNode>A2</dstNode>
				<functionList>NAT FW</functionList>
			</trvPolicy>
		</trvPolicySet>
	</policySet>
</mns:nffgInfo>
